# Generated by Django 6.0 on 2026-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('publish_post', 'Can publish post')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
