# Generated by Django 6.0 on 2025-12-19 18:02

from django.db import migrations


def create_initial_users(apps, schema_editor) -> None:
    User = apps.get_model("auth", "User")

    users = [
        {
            "username": "alice",
            "first_name": "Alice",
            "last_name": "Smith",
            "email": "alice@example.com",
        },
        {
            "username": "bob",
            "first_name": "Bob",
            "last_name": "Brown",
            "email": "bob@example.com",
        },
        {
            "username": "charlie",
            "first_name": "Charlie",
            "last_name": "Johnson",
            "email": "charlie@example.com",
        },
    ]

    for user_data in users:
        User.objects.get_or_create(
            username=user_data["username"],
            defaults=user_data,
        )


def reverse_initial_users(apps, schema_editor) -> None:
    User = apps.get_model("auth", "User")
    User.objects.filter(username__in=["alice", "bob", "charlie"]).delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(
            create_initial_users,
            reverse_initial_users,
        ),
    ]
