apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvc # Фізичне сховище для PostgreSQL
spec:
  capacity:
    storage: 1Gi # Обсяг диску
  volumeMode: Filesystem # Формат, як буде монтуватися
  accessModes:
    - ReadWriteOnce # Доступ для одного pod одночасно
  persistentVolumeReclaimPolicy: Delete # При видаленні PVC дані теж видаляються
  storageClassName: standard # Використовує стандартний storage class
  hostPath:
    path: /tmp/hostpath_pv_pgdata # Локальний шлях на вузлі (для minikube)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc # Запит на виділення обсягу з PV
spec:
  accessModes:
    - ReadWriteOnce # Має відповідати PV вгорі
  resources:
    requests:
      storage: 1Gi # Кількість пам'яті, яку хоче pod
