apiVersion: v1
kind: Service
metadata:
  name: django-backend # Service для доступу до Django backend
spec:
  selector:
    app: django-backend # Service направляє трафік на pod-и з цим label
  ports:
    - port: 8001 # Внутрішній порт service
      targetPort: 8001 # Порт контейнера, куди піде трафік
      nodePort: 30001 # Зовнішній порт вузла для доступу з браузера

  type: NodePort # Відкриває service через IP вузла + nodePort
