apiVersion: v1
kind: Service
metadata:
  name: postgres # Service для доступу до PostgreSQL всередині cluster
spec:
  selector:
    app: postgres # Service направляє трафік на pod PostgreSQL
  ports:
    - port: 5432 # Порт service
      targetPort: 5432 # Порт контейнера PostgreSQL
