apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets # Secret для backend-застосунку
type: Opaque # Стандартний тип для довільних секретних даних
stringData:
  # Налаштування підключення до PostgreSQL
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB_NAME: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  # Django-конфігурація через змінні середовища
  DEBUG: "True"
  SECRET_KEY: xw7r7!46$9#+9lr79px92wxk3w)t-)w#8ctsugjlb^c!bha
  ALLOWED_HOSTS: 127.0.0.1,localhost,192.168.49.2
