# Generated by Django 6.0 on 2025-12-22 18:53

from django.db import migrations


def create_projects(apps, schema_editor) -> None:
    """Створення проектів для користувача в БД."""
    Project = apps.get_model("django_signals", "Project")
    User = apps.get_model("auth", "User")

    backend = Project.objects.create(name="Backend")
    frontend = Project.objects.create(name="Frontend")
    devops = Project.objects.create(name="DevOps")

    # Якщо є користувачі — привʼязуємо першого (той що суперадмін)
    user = User.objects.filter(is_superuser=True).first()
    if user:
        backend.users.add(user)
        frontend.users.add(user)


def delete_projects(apps, schema_editor) -> None:
    """Видалення проектів для зворотної операції migrate."""
    Project = apps.get_model("django_signals", "Project")
    Project.objects.filter(name__in=["Backend", "Frontend", "DevOps"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("django_signals", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_projects, delete_projects),
    ]
