services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-backend
    image: django-backend
    user: django-user
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file: .env
    # запуск бекенду (producer задач)
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:14.6-alpine
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB_NAME
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend

  # Брокер (черга) зберігає задачі в черзі і зберігає результат їх виконання,
  # в своїй базі, якщо налаштовано для задачі
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    user: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - redis-data:/data
    networks:
      - backend

  celery-worker:
    image: django-backend
    container_name: celery-backend-worker
    user: django-user
    hostname: celery
    volumes:
      - .:/app
    # запуск Celery воркер (consumer) для виконання задач з черги (Redis)
    command: celery -A core.celery.app worker -l INFO
    env_file: .env
    healthcheck:
      # перевіряє доступність воркера
      test:
        ["CMD-SHELL", "celery inspect ping - destination celery@celery"]
      interval: 60s
      timeout: 10s
      retries: 2
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - backend

  celery-beat:
    image: django-backend
    container_name: celery-beat-tasks
    user: django-user
    volumes:
      - .:/app
    command: celery -A core.celery.app beat -l INFO
    environment:
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers:DatabaseScheduler
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - backend

  flower:
    image: django-backend
    container_name: flower-tasks-monitoring
    user: django-user
    volumes:
      - .:/app
    command: celery -A core.celery.app flower
    environment:
        # порт на якому доступний моніторинг (127.0.0.1:5555)
      - FLOWER_PORT=5555
        # дозволяє зберігати та відображати вже оброблені задачі
        # після перезавантаження сервісу
      - FLOWER_PERSISTENT=True
        # назва бази даних куди зберігаються дані про задачі
      - FLOWER_DB=flower_db
    env_file: .env
    ports:
      - 5555:5555
    depends_on:
      db:
        condition: service_healthy
      celery-worker:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer-postgres
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1452
