# Generated by Django 5.2.7 on 2025-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='posts_categ_title_162240_idx'),
        ),
    ]
