# Generated by Django 5.2.7 on 2025-11-10 19:24

from django.db import migrations


def create_initial_categories(apps, schema_editor) -> None:
    Category = apps.get_model("posts", "Category")
    for title in ("Python", "Django", "DevOps"):
        Category.objects.create(title=title)


def delete_initial_categories(apps, schema_editor) -> None:
    Category = apps.get_model("posts", "Category")
    for category in Category.objects.all():
        if category.title in ("Python", "Django", "DevOps"):
            category.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post"),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, delete_initial_categories)
    ]
