[project]
name = "my-django-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "postman-collection-exporter>=0.0.9",
]
